import type { Attribute, CardFrame, LinkArrow, SpellTrapType } from "@/types/card";

export const STRINGS = {
    app: {
        title: "Yu-Gi-Oh! Card Maker",
        download: "Download",
        downloadNeedsFrame: "Escolha uma moldura para baixar a carta",
        credit: (year: number) => `© ${year} Desenvolvido por Richard Tavares`,
        linkedIn: "LinkedIn de Richard Tavares",
        gitHub: "GitHub de Richard Tavares",
    },
    exportErrors: {
        "blocked-art": "A imagem da arte vem de um site que não permite exportação. Baixe a imagem e envie como arquivo.",
        "encoding-failed": "Não foi possível gerar a imagem.",
        unknown: "Não foi possível baixar a carta.",
    },
    preview: {
        cardBack: "Verso da carta",
        card: (name: string) => `Carta: ${name}`,
    },
    form: {
        frame: "Moldura",
        attribute: "Atributo",
        level: "Nível",
        rank: "Rank",
        spellType: "Tipo de Magia",
        trapType: "Tipo de Armadilha",
        pendulum: "Pêndulo?",
        name: "Nome",
        linkArrows: "Setas Link",
        art: "Arte",
        artSource: "Origem da arte",
        artFromFile: "Arquivo",
        artFromLink: "Link",
        artUrlPlaceholder: "URL da imagem",
        pendulumScales: "Escalas Pêndulo",
        pendulumScaleLeft: "Escala Pêndulo azul",
        pendulumScaleRight: "Escala Pêndulo vermelha",
        pendulumEffect: "Efeito Pêndulo",
        typeLine: "Tipo",
        setCode: "Edição",
        effect: "Efeito",
        description: "Descrição",
        atk: "Ataque",
        def: "Defesa",
        linkRating: "Classificação Link",
        passcode: "Número de Série",
        copyright: "Direitos Autorais",
        selectPlaceholder: "Selecione",
        yes: "Sim",
        no: "Não",
    },
    frames: {
        normal: "Monstro Normal",
        effect: "Monstro de Efeito",
        fusion: "Monstro de Fusão",
        ritual: "Monstro Ritual",
        synchro: "Monstro Sincro",
        xyz: "Monstro Xyz",
        link: "Monstro Link",
        token: "Token",
        spell: "Magia",
        trap: "Armadilha",
    } satisfies Record<CardFrame, string>,
    attributes: {
        dark: "Trevas",
        divine: "Divino",
        earth: "Terra",
        fire: "Fogo",
        light: "Luz",
        water: "Água",
        wind: "Vento",
        spell: "Magia",
        trap: "Armadilha",
    } satisfies Record<Attribute, string>,
    spellTypes: {
        normal: "Normal",
        "quick-play": "Rápida",
        field: "Campo",
        equip: "Equipamento",
        continuous: "Contínua",
        ritual: "Ritual",
    } satisfies Partial<Record<SpellTrapType, string>>,
    trapTypes: {
        normal: "Normal",
        continuous: "Contínua",
        counter: "Resposta",
    } satisfies Partial<Record<SpellTrapType, string>>,
    linkArrows: {
        "top-left": "Seta superior esquerda",
        top: "Seta superior",
        "top-right": "Seta superior direita",
        left: "Seta esquerda",
        right: "Seta direita",
        "bottom-left": "Seta inferior esquerda",
        bottom: "Seta inferior",
        "bottom-right": "Seta inferior direita",
    } satisfies Record<LinkArrow, string>,
    capacity: {
        fontSize: (px: number) => `Fonte ${px}px`,
        condensed: (percent: number) => `Texto comprimido ${percent}%`,
        overflow: "Não cabe na caixa desta moldura: reduza o texto",
        full: "A caixa de texto da carta está cheia.",
        trimmed: "O texto colado foi ajustado ao espaço da carta.",
    },
    card: {
        spellLabel: "Card de Magia",
        trapLabel: "Card de Armadilha",
    },
} as const;
